""" Even Fibonacci Numbers
-----------------------------------
Each Fibonacci term is generated by adding the previous two. Starting for 1 and 2, 
the first 10 are: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
Find the sum of the even terms whose value doesn't exceed n. """

def even_fibonacci_sum(n):
    """ every third fibonacci is even: Gn = F3n, Sn = Σ[0..n]Gi
    Gn: 0, 2, 8, 34, 144, 610, 2584, ...
    Sn: 0, 2, 10, 44, 188, 798, 3382, ... """
    a, b =  0, 2
    """ G0 = 0, G1 = 2 
    Gn+2 = 4Gn+1 + Gn """
    while b <= n:
        a, b = b, a + 4 * b
    """ Sn = (Gn + Gn+1 - 2) / 4 """
    return (b + a - 2) // 4

if __name__ == "__main__":
    print(even_fibonacci_sum(4_000_000))
