"""
Even Fibonacci Numbers
--------------------------
Each Fibonacci term is generated by adding the previous two. Starting for 1 and 2, the first 10 are: 1, 2, 3, 5, 8, 13, 
21, 34, 55, 89, ...
Find the sum of the even terms whose value doesn't exceed n.
"""

def even_fibonacci_sum(n):
    f1, f2 = 1, 2
    s = 0
    while f2 <= n:
        if f2 % 2 == 0:
            s += f2
        """
        update Fibonacci numbers for the next iteration by assigning f2 to the sum of the previous two, 
        and updating f1 to the previous f2, effectively skipping odd terms
        """
        f1, f2 = f2, f1 + f2
    return s   

print(even_fibonacci_sum(4_000_000))
